[advisories]
ignore = [
    "RUSTSEC-2024-0429", # glib unsoundness (waiting for upstream fix in tauri dependencies)
    "RUSTSEC-2024-0411", # gdkwayland-sys unmaintained
    "RUSTSEC-2024-0417", # gdkx11 unmaintained
    "RUSTSEC-2024-0414", # gdkx11-sys unmaintained
    "RUSTSEC-2024-0415", # gtk unmaintained
    "RUSTSEC-2024-0419", # gtk3-macros unmaintained
    "RUSTSEC-2024-0420", # gtk-sys unmaintained
    "RUSTSEC-2024-0384", # instant unmaintained
    "RUSTSEC-2024-0370", # proc-macro-error unmaintained
    "RUSTSEC-2025-0119", # number_prefix unmaintained
    "RUSTSEC-2025-0081", # unic-char-property unmaintained
    "RUSTSEC-2025-0075", # unic-char-range unmaintained
    "RUSTSEC-2025-0080", # unic-common unmaintained
    "RUSTSEC-2025-0100", # unic-ucd-ident unmaintained
    "RUSTSEC-2025-0098", # unic-ucd-version unmaintained
]
