# audit.toml
# Ignored vulnerabilities for cargo-audit

[advisories]
ignore = [
    # gdkwayland-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0411",
    # gdkx11: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0417",
    # gdkx11-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0414",
    # gtk: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0415",
    # gtk-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0420",
    # gtk3-macros: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0419",
    # instant: `instant` is unmaintained
    "RUSTSEC-2024-0384",
    # number_prefix: number_prefix crate is unmaintained
    "RUSTSEC-2025-0119",
    # proc-macro-error: proc-macro-error is unmaintained
    "RUSTSEC-2024-0370",
    # unic-char-property: `unic-char-property` is unmaintained
    "RUSTSEC-2025-0081",
    # unic-common: `unic-common` is unmaintained
    "RUSTSEC-2025-0080",
    # unic-ucd-ident: `unic-ucd-ident` is unmaintained
    "RUSTSEC-2025-0100",
    # unic-ucd-version: `unic-ucd-version` is unmaintained
    "RUSTSEC-2025-0098",
    # unic-char-range: `unic-char-range` is unmaintained
    "RUSTSEC-2025-0075",
    # glib: Unsoundness in `Iterator` and `DoubleEndedIterator` impls
    # Transitive dependency of webkit2gtk/tauri, difficult to update manually without breaking changes
    "RUSTSEC-2024-0429"
]
