# audit.toml - Configuration for cargo-audit

[advisories]
ignore = [
    "RUSTSEC-2024-0411", # gdkwayland-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0417", # gdkx11: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0414", # gdkx11-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0415", # gtk: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0420", # gtk-sys: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0419", # gtk3-macros: gtk-rs GTK3 bindings - no longer maintained
    "RUSTSEC-2024-0384", # instant: `instant` is unmaintained
    "RUSTSEC-2025-0119", # number_prefix: crate is unmaintained
    "RUSTSEC-2024-0370", # proc-macro-error: unmaintained
    "RUSTSEC-2024-0429", # glib: Unsoundness in `Iterator` impls for `glib::VariantStrIter`
    "RUSTSEC-2025-0081", # unic-char-property: unmaintained
    "RUSTSEC-2025-0075", # unic-char-range: unmaintained
    "RUSTSEC-2025-0080", # unic-common: unmaintained
    "RUSTSEC-2025-0100", # unic-ucd-ident: unmaintained
    "RUSTSEC-2025-0098", # unic-ucd-version: unmaintained
]
