[workspace]
resolver = "2"
members = ["apps/core", "apps/tauri"]

[workspace.package]
version = "1.0.3"
edition = "2021"
authors = ["n24q02m"]
license = "MIT"
repository = "https://github.com/n24q02m/EchoVault"

[profile.release]
strip = true
lto = true
codegen-units = 1
